AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  region:
    Type: String
  googleRedirectUrl:
    Type: String
  googleClientSecret:
    Type: String
  authTableName:
    Type: String
  profileTableName:
    Type: String

Description: >
  tsubuyaki-tune

  Sample SAM Template for tsubuyaki-tune
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  # ========================================================================================================
  # DynamoDB
  # ========================================================================================================
  TT-UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref authTableName
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  TT-ProfileTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref profileTableName
      KeySchema:
        - AttributeName: uid
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: uid
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  # ========================================================================================================
  # APIGateway
  # ========================================================================================================
  TT-ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      EndpointConfiguration:
        Type: REGIONAL # リージョン最適化に設定
      Auth:
        DefaultAuthorizer: TokenAuthorizer # デフォルトの認可をトークンオーソライザーに設定
        AddApiKeyRequiredToCorsPreflight: false
        Authorizers:
          TokenAuthorizer:
            FunctionArn: !GetAtt TokenAuthorizerFunction.Arn # SAMとapp.tsで作ったラムダ関数
        AddDefaultAuthorizerToCorsPreflight: false # Preflight requestの認可を除外するための設定
      Cors:
        AllowMethods: "'GET,OPTIONS,POST'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
    Metadata:
      SamResourceId: TT-ApiGateway
  # ========================================================================================================
  # オーソライズ関数
  # ========================================================================================================
  TokenAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend-lambda/
      Handler: app.tokenAuthorizerFunction
      Runtime: nodejs18.x
    Metadata:
      SamResourceId: TokenAuthorizerFunction
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension: # 拡張子を.mjにすることでAWSのコンソールで表示できる
          - .js=.mjs
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
        External:
          - "@aws-sdk/client-dynamodb"
          - "@aws-sdk/lib-dynamodb"
  # ========================================================================================================
  # GoogleSingIn関数
  # ========================================================================================================
  GoogleSingInFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend-lambda
      Handler: app.googleSignInFunction
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        GoogleSignIn:
          Type: Api
          Properties:
            Path: /oauth/google/signin
            Method: post
            RestApiId:
              Ref:TT-ApiGateway
      # Lambdaの環境変数
      Environment:
        Variables:
          RedirectUri: !Ref googleRedirectUrl
          ClientSecret: !Ref googleClientSecret
          AuthTableName: !Ref authTableName
          ProfileTableName: !Ref profileTableName
          Region: !Ref region
      Policies:
        - AmazonDynamoDBFullAccess
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension: # 拡張子を.mjにすることでAWSのコンソールで表示できる
          - .js=.mjs
        Target: "es2020"
        UseNpmCi: true
        Sourcemap: true
        EntryPoints:
          - app.ts
        External: # 外部パッケージの追加（ビルドの際に除外される）
          - "https"
          - "@aws-sdk/client-dynamodb"
          - "@aws-sdk/lib-dynamodb"
# ========================================================================================================
# 作成したスタック内のリソースの情報を標準出力に表示する
# ========================================================================================================
Outputs:
  # GoogleSignInAPI
  GoogleSingInFunction:
    Description: "Google OAuth Lambda Function ARN"
    Value: !Sub "https://${TsubuyakiTuneApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Dev/oauth/google/signin"
