AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  region:
    Type: String
  googleRedirectUrl:
    Type: String
  googleClientSecret:
    Type: String
  authTableName:
    Type: String
  profileTableName:
    Type: String
  tsubuyakiTableName:
    Type: String

Description: >
  tsubuyaki-tune

  Sample SAM Template for tsubuyaki-tune

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  # ========================================================================================================
  # DynamoDB
  # ========================================================================================================
  TTProfileTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref profileTableName
      KeySchema:
        - AttributeName: profileId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: profileId
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  TTTsubuyakiTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref tsubuyakiTableName
      KeySchema:
        - AttributeName: tsubuyakiId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: tsubuyakiId
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  # ========================================================================================================
  # APIGateway 認可あり
  # ========================================================================================================
  TsubuyakiTuneApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      EndpointConfiguration:
        Type: REGIONAL # リージョン最適化に設定
      Auth:
        DefaultAuthorizer: TokenAuthorizer # デフォルトの認可をトークンオーソライザーに設定
        AddApiKeyRequiredToCorsPreflight: false
        Authorizers:
          TokenAuthorizer:
            FunctionArn: !GetAtt TokenAuthorizerFunction.Arn # SAMとapp.tsで作ったラムダ関数
        AddDefaultAuthorizerToCorsPreflight: false # Preflight requestの認可を除外するための設定
      Cors:
        AllowMethods: "'GET,OPTIONS,POST'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
    Metadata:
      SamResourceId: TsubuyakiTuneApiGateway

  TokenAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend-lambda/
      Handler: app.tokenAuthorizerFunction
      Runtime: nodejs18.x
      Environment:
        Variables:
          AuthTableName: !Ref authTableName
          ProfileTableName: !Ref profileTableName
          TsubuyakiTableName: !Ref tsubuyakiTableName
          Region: !Ref region
      Policies:
        - AmazonDynamoDBFullAccess # TODO: readだけでいい
    Metadata:
      SamResourceId: TokenAuthorizerFunction
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension: # 拡張子を.mjにすることでAWSのコンソールで表示できる
          - .js=.mjs
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
        External:
          - "@aws-sdk/client-dynamodb"
          - "@aws-sdk/lib-dynamodb"
  # ========================================================================================================
  # FetchProfile関数
  # ========================================================================================================
  FetchProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend-lambda
      Handler: app.fetchProfileFunction
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        AddTsubuyaki:
          Type: Api
          Properties:
            Path: /profile/fetch
            Method: get
            RestApiId:
              !Ref TsubuyakiTuneApiGateway
      # Lambdaの環境変数
      Environment:
        Variables:
          AuthTableName: !Ref authTableName
          ProfileTableName: !Ref profileTableName
          TsubuyakiTableName: !Ref tsubuyakiTableName
          Region: !Ref region
      Policies:
        - AmazonDynamoDBFullAccess
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension: # 拡張子を.mjにすることでAWSのコンソールで表示できる
          - .js=.mjs
        Target: "es2020"
        UseNpmCi: true
        Sourcemap: true
        EntryPoints:
          - app.ts
        External: # 外部パッケージの追加（ビルドの際に除外される）
          - "https"
          - "@aws-sdk/client-dynamodb"
          - "@aws-sdk/lib-dynamodb"
  # ========================================================================================================
  # AddTsubuyaki関数
  # ========================================================================================================
  AddTsubuyakiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend-lambda
      Handler: app.addTsubuyakiFunction
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        AddTsubuyaki:
          Type: Api
          Properties:
            Path: /tsubuyaki/add
            Method: post
            RestApiId:
              !Ref TsubuyakiTuneApiGateway
      # Lambdaの環境変数
      Environment:
        Variables:
          AuthTableName: !Ref authTableName
          ProfileTableName: !Ref profileTableName
          TsubuyakiTableName: !Ref tsubuyakiTableName
          Region: !Ref region
      Policies:
        - AmazonDynamoDBFullAccess
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension: # 拡張子を.mjにすることでAWSのコンソールで表示できる
          - .js=.mjs
        Target: "es2020"
        UseNpmCi: true
        Sourcemap: true
        EntryPoints:
          - app.ts
        External: # 外部パッケージの追加（ビルドの際に除外される）
          - "https"
          - "@aws-sdk/client-dynamodb"
          - "@aws-sdk/lib-dynamodb"
  # ========================================================================================================
  # FetchTsubuyaki関数
  # ========================================================================================================
  FetchTsubuyakiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend-lambda
      Handler: app.fetchTsubuyakiFunction
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        AddTsubuyaki:
          Type: Api
          Properties:
            Path: /tsubuyaki/fetch
            Method: get
            RestApiId:
              !Ref TsubuyakiTuneApiGateway
      # Lambdaの環境変数
      Environment:
        Variables:
          AuthTableName: !Ref authTableName
          ProfileTableName: !Ref profileTableName
          TsubuyakiTableName: !Ref tsubuyakiTableName
          Region: !Ref region
      Policies:
        - AmazonDynamoDBFullAccess
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension: # 拡張子を.mjにすることでAWSのコンソールで表示できる
          - .js=.mjs
        Target: "es2020"
        UseNpmCi: true
        Sourcemap: true
        EntryPoints:
          - app.ts
        External: # 外部パッケージの追加（ビルドの際に除外される）
          - "https"
          - "@aws-sdk/client-dynamodb"
          - "@aws-sdk/lib-dynamodb"
# ========================================================================================================
# 作成したスタック内のリソースの情報を標準出力に表示する
# ========================================================================================================
Outputs:
  # FetchProfileAPI
  FetchProfileFunction:
    Description: "[GET]Fetch Tsubuyaki Lambda Function ARN"
    Value: !Sub "https://${TsubuyakiTuneApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Dev/profile/fetch"
  # AddTsubuyakiAPI
  AddTsubuyakiFunction:
    Description: "[POST]Add Tsubuyaki Lambda Function ARN"
    Value: !Sub "https://${TsubuyakiTuneApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Dev/tsubuyaki/add"
  # FetchTsubuyakiAPI
  FetchTsubuyakiFunction:
    Description: "[GET]Fetch Tsubuyaki Lambda Function ARN"
    Value: !Sub "https://${TsubuyakiTuneApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Dev/tsubuyaki/fetch"